In [3]:
import pickle

nLabel, nTrial, nUser, nChannel, nTime  = 4, 40, 32, 40, 8064
no_of_users=32
def convertData():
    print("Program started"+"\n")
    fout_data = open("D:/Major Project/data/features_raw.dat",'w')
    fout_labels0 = open("D:/Major Project/data/labels_0.dat",'w')
    fout_labels1 = open("D:/Major Project/data/labels_1.dat",'w')
    fout_labels2 = open("D:/Major Project/data/labels_2.dat",'w')
    fout_labels3 = open("D:/Major Project/data/labels_3.dat",'w')
    for i in range(no_of_users):  #nUser #4, 40, 32, 40, 8064 4 labels, 40 sample for each user, 32 such user, 40 electrode, 8064*40 features
        if(i%1 == 0):
            if i < 10:
                name = '%0*d' % (2,i+1)
            else:
                name = i+1
        fname = "D:/Major Project/data_preprocessed_python/s"+str(name)+".dat"     
        f = open(fname, 'rb')                 #Read the file in Binary mode
        x = pickle.load(f, encoding='latin1')
        print(fname)                          
    	
        for tr in range(nTrial):
            if(tr%1 == 0):
                for dat in range(nTime):
                    if(dat%32 == 0):
                        for ch in range(nChannel):
                            fout_data.write(str(x['data'][tr][ch][dat]) + " ");
                fout_labels0.write(str(x['labels'][tr][0]) + "\n");
                fout_labels1.write(str(x['labels'][tr][1]) + "\n");
                fout_labels2.write(str(x['labels'][tr][2]) + "\n");
                fout_labels3.write(str(x['labels'][tr][3]) + "\n");
                fout_data.write("\n");
    fout_labels0.close()
    fout_labels1.close()
    fout_labels2.close()
    fout_labels3.close()
    fout_data.close()
    print("\n"+"Print Successful")

if __name__ == '__main__':
    convertData()

Program started

D:/Major Project/data_preprocessed_python/s01.dat
D:/Major Project/data_preprocessed_python/s02.dat
D:/Major Project/data_preprocessed_python/s03.dat
D:/Major Project/data_preprocessed_python/s04.dat
D:/Major Project/data_preprocessed_python/s05.dat
D:/Major Project/data_preprocessed_python/s06.dat
D:/Major Project/data_preprocessed_python/s07.dat
D:/Major Project/data_preprocessed_python/s08.dat
D:/Major Project/data_preprocessed_python/s09.dat
D:/Major Project/data_preprocessed_python/s10.dat
D:/Major Project/data_preprocessed_python/s11.dat
D:/Major Project/data_preprocessed_python/s12.dat
D:/Major Project/data_preprocessed_python/s13.dat
D:/Major Project/data_preprocessed_python/s14.dat
D:/Major Project/data_preprocessed_python/s15.dat
D:/Major Project/data_preprocessed_python/s16.dat
D:/Major Project/data_preprocessed_python/s17.dat
D:/Major Project/data_preprocessed_python/s18.dat
D:/Major Project/data_preprocessed_python/s19.dat
D:/Major Project/data_preprocesse

In [4]:
import pickle

nLabel, nTrial, nUser, nChannel, nTime  = 4, 40, 32, 40, 8064  #10080/80=126*40=5040 features
no_of_users=32
def sampleFeatures():
    print("Program started"+"\n")
    fout_data = open('D:/Major Project/data/features_sampled.dat','w')
    for i in range(no_of_users):   #nUser  #4, 40, 32, 40, 8064
        if(i%1 == 0):
            if i < 10:			
                name = '%0*d' % (2,i+1)
            else:
                name = i+1		
            fname = "D:/Major Project/data_preprocessed_python/s"+str(name)+".dat"
            x = pickle.load(open(fname, 'rb'), encoding='latin1')		
            print(fname)		
            for tr in range(nTrial):			
                if(tr%1 == 0):				
                    for dat in range(nTime):					
                        if(dat%32 == 0 ):						
                            for ch in range(nChannel):							
                                fout_data.write(str(ch+1) + " ");							
                                fout_data.write(str(x['data'][tr][ch][dat]) + " ");			
                fout_data.write("\n");
    fout_data.close()
    print('Completed')

if __name__ == '__main__':
    sampleFeatures()

Program started

D:/Major Project/data_preprocessed_python/s01.dat
D:/Major Project/data_preprocessed_python/s02.dat
D:/Major Project/data_preprocessed_python/s03.dat
D:/Major Project/data_preprocessed_python/s04.dat
D:/Major Project/data_preprocessed_python/s05.dat
D:/Major Project/data_preprocessed_python/s06.dat
D:/Major Project/data_preprocessed_python/s07.dat
D:/Major Project/data_preprocessed_python/s08.dat
D:/Major Project/data_preprocessed_python/s09.dat
D:/Major Project/data_preprocessed_python/s10.dat
D:/Major Project/data_preprocessed_python/s11.dat
D:/Major Project/data_preprocessed_python/s12.dat
D:/Major Project/data_preprocessed_python/s13.dat
D:/Major Project/data_preprocessed_python/s14.dat
D:/Major Project/data_preprocessed_python/s15.dat
D:/Major Project/data_preprocessed_python/s16.dat
D:/Major Project/data_preprocessed_python/s17.dat
D:/Major Project/data_preprocessed_python/s18.dat
D:/Major Project/data_preprocessed_python/s19.dat
D:/Major Project/data_preprocesse

In [5]:
def onehotencoding0():
    print("Program started"+"\n")
    fout_labels_class = open("D:/Major Project/data/label_class_0.dat",'w')
    
    with open('D:/Major Project/data/labels_0.dat','r') as f:
        for val in f:
            if float(val) > 4.5:
                fout_labels_class.write(str(1) + "\n");
            else:
                fout_labels_class.write(str(0) + "\n");
                
    print("Encoded label 0"+"\n")
if __name__ == '__main__':
    onehotencoding0()

Program started

Encoded label 0



In [6]:
def onehotencoding1():
    print("Program started"+"\n")
    fout_labels_class = open("D:/Major Project/data/label_class_1.dat",'w')
    
    with open('D:/Major Project/data/labels_1.dat','r') as f:
        for val in f:
            if float(val) > 4.5:
                fout_labels_class.write(str(1) + "\n");
            else:
                fout_labels_class.write(str(0) + "\n");
    print("Encoded label 1"+"\n")
if __name__ == '__main__':
    onehotencoding1()

Program started

Encoded label 1



In [8]:
def onehotencoding1():
    print("Program started"+"\n")
    fout_labels_class = open("D:/Major Project/data/label_class_2.dat",'w')
    
    with open('D:/Major Project/data/labels_2.dat','r') as f:
        for val in f:
            if float(val) > 4.5:
                fout_labels_class.write(str(1) + "\n");
            else:
                fout_labels_class.write(str(0) + "\n");
    print("Encoded label 2"+"\n")
if __name__ == '__main__':
    onehotencoding1()

Program started

Encoded label 2



In [9]:
def onehotencoding3():
    print("Program started"+"\n")
    fout_labels_class = open("D:/Major Project/data/label_class_3.dat",'w')
    
    with open('D:/Major Project/data/labels_3.dat','r') as f:
        for val in f:
            if float(val) > 4.5:
                fout_labels_class.write(str(1) + "\n");
            else:
                fout_labels_class.write(str(0) + "\n");
    print("Encoded label 3"+"\n")
if __name__ == '__main__':
    onehotencoding3()

Program started

Encoded label 3



In [ ]:
def data_visual():
    import pandas as pd
    import seaborn as sns
    from pandas.plotting import scatter_matrix
    import matplotlib.pyplot as plt
    import warnings
    
    warnings.filterwarnings("ignore")
    features = pd.read_csv('features.csv') 
    labels = pd.read_csv('labels.csv')

    names = ['valence', 'arousal', 'dominance', 'liking']
    dataset =features.transpose().reindex()


# Summary of dataset
    print('Summary of dataset\n')
# shape
    print('1. Shape is:')
    print(dataset.shape)
# head
    print('\n2. First 8 rows are as:')
    print(dataset.head(8))
# descriptions
    print('\n3. Statistical description:')
    print(dataset.describe())
    types = dataset.dtypes
    print('\n4. Data Types:')
    print(types)

# Data visualisation
# box and whisker plots
    for i in range(5):
        sns.set_style('whitegrid')
        sns.boxplot(dataset[i])
        plt.title('Magnitude versus ' + str(i+1) + ' channel')
        plt.show()
    
    import seaborn as sns
    from matplotlib import pyplot as plt
    for i in range(5):
        sns.distplot(dataset[i])
        plt.title('Magnitude versus ' + str(i+1) + ' channel')
        plt.show()
if __name__ == '__main__':
   data_visual()

In [1]:
import numpy
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

def knn_classifier():
    file_x = 'D:/Major Project/data/features_sampled.dat'
    file_y = 'D:/Major Project/data/label_class_0.dat'
    
    X = numpy.genfromtxt(file_x, delimiter=' ')
    y = numpy.genfromtxt(file_y, delimiter=' ')
    
    # Split the data into training/testing sets
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
    
    # Feature Scaling
    from sklearn.preprocessing import StandardScaler
    sc = StandardScaler()
    X_train = sc.fit_transform(X_train)
    X_test = sc.transform(X_test)
    	
    # KNN
    clf = KNeighborsClassifier(n_neighbors=1)
    clf.fit(X_train, y_train)
    y_predict = clf.predict(X_test)
    cm = confusion_matrix(y_test, y_predict)
    print(cm)
    print("Accuracy score of Valence ")
    print(accuracy_score(y_test, y_predict)*100)
    
    
    
    ###############################################################################
    
    file_x = 'D:/Major Project/data/features_sampled.dat'
    file_y = 'D:/Major Project/data/label_class_1.dat'
    
    X = numpy.genfromtxt(file_x, delimiter=' ')
    y = numpy.genfromtxt(file_y, delimiter=' ')
    
    # Split the data into training/testing sets
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
    
    # Feature Scaling
    from sklearn.preprocessing import StandardScaler
    sc = StandardScaler()
    X_train = sc.fit_transform(X_train)
    X_test = sc.transform(X_test)
    	
    # KNN
    clf = KNeighborsClassifier(n_neighbors=1)
    clf.fit(X_train, y_train)
    y_predict = clf.predict(X_test)
    cm = confusion_matrix(y_test, y_predict)
    print(cm)
    print("Accuracy score of Arousal ")
    print(accuracy_score(y_test, y_predict)*100)
    
    
    ###############################################################################
    
    file_x = 'D:/Major Project/data/features_sampled.dat'
    file_y = 'D:/Major Project/data/label_class_2.dat'
    
    X = numpy.genfromtxt(file_x, delimiter=' ')
    y = numpy.genfromtxt(file_y, delimiter=' ')
    
    # Split the data into training/testing sets
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
    
    # Feature Scaling
    from sklearn.preprocessing import StandardScaler
    sc = StandardScaler()
    X_train = sc.fit_transform(X_train)
    X_test = sc.transform(X_test)
    	
    # KNN
    clf = KNeighborsClassifier(n_neighbors=1)
    clf.fit(X_train, y_train)
    y_predict = clf.predict(X_test)
    cm = confusion_matrix(y_test, y_predict)
    print(cm)
    print("Accuracy score of Dominance ")
    print(accuracy_score(y_test, y_predict)*100)
    
    
    ###############################################################################
    
    file_x = 'D:/Major Project/data/features_sampled.dat'
    file_y = 'D:/Major Project/data/label_class_3.dat'
    
    X = numpy.genfromtxt(file_x, delimiter=' ')
    y = numpy.genfromtxt(file_y, delimiter=' ')
    
    # Split the data into training/testing sets
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
    
    # Feature Scaling
    from sklearn.preprocessing import StandardScaler
    sc = StandardScaler()
    X_train = sc.fit_transform(X_train)
    X_test = sc.transform(X_test)
    	
    # KNN
    clf = KNeighborsClassifier(n_neighbors=1)
    clf.fit(X_train, y_train)
    y_predict = clf.predict(X_test)
    cm = confusion_matrix(y_test, y_predict)
    print(cm)
    print("Accuracy score of Liking ")
    print(accuracy_score(y_test, y_predict)*100)
    
    
    
       
    
if __name__ == '__main__':
    knn_classifier()

[[ 43  48]
 [ 63 102]]
Accuracy score of Valence 
56.640625
[[ 30  60]
 [ 52 114]]
Accuracy score of Arousal 
56.25
[[ 14  62]
 [ 21 159]]
Accuracy score of Dominance 
67.578125
[[  1  78]
 [ 11 166]]
Accuracy score of Liking 
65.234375
